### ISSUE TITLE
LNPopupController 3.0 tracking

### ISSUE THREAD

**Issue by LeoNatan** [LeoNatan/LNPopupController#348]
I've started work on 3.0.

It is intended as a general rewrite of the entire presentation model. The idea is to use `UIPresentationController` subclasses with custom animation and interaction controllers. (#225)
This will greatly simplify the presentation system and allow many more features, such as "free" card presentation on iOS 13.

Planned features that will also make the cut for 3.0:
- Animations that run alongside the presentation animations of the popup (#211)
- Supporting card presentations (iOS 13, for now, but can be any OS version with a custom presentation controller) (#143)
- Dimming of contents under the popup (#325)
- Remove legacy iOS support (#335)

The goal is to support as much of the current feature set, as possible. Some minor changes to look and feel might happen due to the transition to presentation controllers. There are still some unknowns.

The effort is being implemented in the `v3_0` branch.
So far, I have removed all legacy code, removed all old presentation code and have a proof of concept using the iOS 13 card presentation controller as the basis for popup presentation.

Todo:
- [x] Add support for full screen popup presentation
- [ ] Add support for interactive ("Drag") presentation
- [x] Add support for iOS 13 interactive card presentation
- [x] Explore card presentations for iOS 12 and below
- [x] Explore non-full width presentations
- [ ] Explore embedding the popup bar inside bottom bars, such as tab bars
- [ ] Explore the possibility of the bar's background view extending under the hosting view's safe areas

**Comment by iDevelopper** [comment]
Hi @LeoNatan , what about the progress of this WIP? Interactive presentations?

Do you have a little bit of time for that?

**Comment by LeoNatan** [comment]
Hello

I have not worked on this in some time. I have ideas, but haven't had the time. I hope to sit again on this branch soon.

**Comment by aidev1065** [comment]
Any updates on this?

**Comment by LeoNatan** [comment]
Sorry, unfortunately I have not worked on this branch (or the framework) in a long while.

**Comment by LeoNatan** [comment]
https://developer.apple.com/documentation/uikit/uisheetpresentationcontroller?language=objc

This API now being public, including all the detents stuff, 3.0 can be implemented much more easily.

**Comment by purepure** [comment]
Love this lib. For here to say thank and also interested in this feature. Any update for 2023 ?
Thank!

**Comment by LeoNatan** [comment]
Hello, unfortunately, I have not made progress on 3.0, and the branch I once worked on is hopelessly outdated now. 

Which feature specifically are you interested in?

**Comment by purepure** [comment]
Hopefully you got sometime and continue improve this lib. It is so great!
I am looking for ability of controlling drag/scroll event for something like Apple Music where they tint the background color or scale the Album cover bigger/smaller when user drag down/up. It make the movement become more attractive.
Anw, I think I can try difference approaching.
Thank you for the lib!

**Comment by LeoNatan** [comment]
I’ll close this issue. I don’t think what I once worked on can be resurrected. I have ideas how to implement transitions and animations. The rest (switching to UIPresentationController presentations) is just a huge undertaking that I don’t really have the time or will for, while Apple itself has abandoned their designs where non-full screen presentation was a thing.
