### ISSUE TITLE
Add support for iOS 10 style popup bar look, presentation and behavior

### ISSUE THREAD

**Issue by LeoNatan** [LeoNatan/LNPopupController#91]
Since the popup bar look, presentation and behavior have changed dramatically, I plan to make changes to the library to **add** support to the library. Developer will have the option to choose between iOS 9 & 10 look, presentation and behavior.

Suggestions are welcome.

---

Status:
- [x] Add 3D Touch Support - #93 
- [x] Implement iOS 10 Popup Bar Look & Interaction Style - #95
- [x] Implement iOS 10 Popup Content View Look & Interaction Styles - #96

**Comment by jahnsrud** [comment]
👍
